### ISSUE TITLE
need a new password reset option

### ISSUE THREAD

**Issue by denislepage** [BirdStudiesCanada/NatureCounts-TO-DO#10]
The NatureCounts password reminder need to be changed to a reset option. Some of those functionalities are already built in Java.  Previous approaches can't be removed until the transition has been completed in all applications.

- set up a new page to handle reset requests (enter email or login name) and allow entering new password
- set up a link where the reset process could be initiated by a link (e.g. within an email)
- set up a page (or instructions on the new page) that allows users to create a password for new accounts.
- deprecate the old Java password reset methods 
- ensure that all users have a salt and hash.

Also need a process for new participants imported (e.g. from Raiser's Edge), whom may not already have a login name and password. In those cases:

- login name is set as the email address (users can change it once they've successfully logged in)
- password fields are left blank
- pw_must_change is set to yes (though I am not sure it matters)

The import process "could" generate the email going out to participants with instructions on how to access their account and generate a new password, or we could send it separately (either from a Java/DB process, or something else entirely).

**Comment by denislepage** [comment]
This is already pretty close:
https://sandbox.birdscanada.org/birdmon/default/pwordreset.jsp

We also need to change the profile page. In order to change their password, people will need to enter their current password and their new password (twice).

**Comment by denislepage** [comment]
OK, done in sandbox, I think. Needs a bit more testing, but I think I have accounted for most/all possibilities?

I have changed the login page and removed the reminder button, as well as the reminder methods in readvar.

I have added a new page for the password reset (link above). The same page is used to link from the password reset email. 

One could generate the token by using a link like this, for instance: 

https://sandbox.birdscanada.org/birdmon/default/pwordreset.jsp?pword_reset=user@email.com
or https://sandbox.birdscanada.org/birdmon/default/pwordreset.jsp?pword_reset=loginname

I have modified the profile and the registration pages. There are various permutations possible, and checking should also be done by comparing to the database after each save (with and without errors).

**I will need to remember to change the link sent by email (www and not sandbox) once testing is done.**

**Comment by cjardine-bsc** [comment]
An error occurred at line: 24 in the jsp file: /monitoring/pwordreset.jsp
The password reset page is returning a compile class error

From: https://www.birdscanada.org/birdmon/default/pwordreset.jsp 

The method resetPword(ProjInfo, String, String, String, String, Tools.PwordResetMessage) in the type Tools is not applicable for the arguments (MonitoringProjInfo, String, String, String, String)
21: 		MonitoringUserInfo userInfo = project.getContactUserInfo();
22: 		String email = (userInfo != null?userInfo.getEmail():null);
23: 		if (email == null) email = "support@birdscanada.org";
24: 		boolean found = Tools.resetPword(projInfo, pwreset, "https://www.birdscanada.org/birdmon/" + projCode + "/pwordreset.jsp", project.getProjectName().getText(lang), email);
25: 		if (found) errormsg.add("pwreset_sent");
26: 		else errormsg.add("pwreset_notfound");
27: 	}

**Comment by denislepage** [comment]
OK, should be fixed. This was done to support translation, which should now be in place (correctly).
