### ISSUE TITLE
terms and conditions thowing 404 error

### ISSUE THREAD

**Issue by cjardine-bsc** [BirdStudiesCanada/NatureCounts-TO-DO#22]
The terms and conditions link on all pages is throwing a 404 error. 

https://www.birdscanada.org/birdmon/default/terms.jsp

**Comment by denislepage** [comment]
Weird. These terms are normally taken from the database, but there should be a page to lay them out.

I am sure it worked at some point.

Ah, here’s the proof:
https://web.archive.org/web/20170716214538/https://www.birdscanada.org/birdmon/default/terms.jsp<https://web.archive.org/web/20170716214538/https:/www.birdscanada.org/birdmon/default/terms.jsp>

**Comment by denislepage** [comment]
Ha-ah. I accidentally moved to the the archive folder at the end of July when doing some summer cleaning.

Restored now.

**Comment by cjardine-bsc** [comment]
Looks like you also tidied aways the two readme_en and _fr files. Those are needed as they are included in the dataset downloads from NCs as instructions on how to work with the .txt files. I'm restoring those.

**Comment by cjardine-bsc** [comment]
yup.
