### ISSUE TITLE
prCreateAtlasMaps fails for MMP re: no country codes

### ISSUE THREAD

**Issue by cjardine-bsc** [BirdStudiesCanada/NatureCounts-TO-DO#36]
Look at locs for MMP and ensure country code is populated in BMDE. 

Can happen after everything has moved over to NCs instead of bscdata.

**Comment by denislepage** [comment]
There are processes that I have set up to overlay all records in loc_id, and assign country, province, squares, etc.

I’ll have to check, but I think those are run in Java. We can look into it once the loc records have been moved.

**Comment by denislepage** [comment]
EXEC prLocFindUtmSquares
