### ISSUE TITLE
TMKN - name of downloaded files

### ISSUE THREAD

**Issue by apdrp** [BirdStudiesCanada/NatureCounts-TO-DO#40]
Would it be possible for files downloaded via the TMKN to have TMKN instead of bmde in their name? Eg _tmkn_req_ebutterfly_12345_ instead of _bmde_req_ebutterfly_12345_ and _tmkn_data_ instead of _bmde_data_.
The idea is always to avoid confusion among TMKN users.

**Comment by denislepage** [comment]
The name needs to be consistent for all files. I will switch to naturecounts_* instead of bmde_.
