### ISSUE TITLE
English to French between BSC CMMN index to NC CMMN trends page

### ISSUE THREAD

**Issue by DMEthier** [BirdStudiesCanada/NatureCounts-TO-DO#47]
Navigating from the BSC CMMN index page: https://www.birdscanada.org/volunteer/cmmn/index.jsp?lang=EN

To the NatureCounts page using the 'Data' or 'Species Trends' buttons on the left hand side brings me to the French page: https://www.bsc-eoc.org/birdmon/cmmn/popindices.jsp?switchlang=FR&switchlang=FR

**Comment by cjardine-bsc** [comment]
fixed on BSC site.
